services:
  - type: web
    name: spruce-test-service
    env: node
    repo: https://github.com/FMOTRDev2025/SpruceTest
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
